spring:
  datasource:
    username: kachmura
    password: <password>
    url: jdbc:sqlserver://morfeusz.wszib.edu.pl:1433;databaseName=kachmura;encrypt=false;
  jpa:
    hibernate:
      ddl-auto: update
